services:
  db:
    container_name: 'db'
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5431:5432'
    networks:
      - custom
  db_test:
    container_name: 'db_test'
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_DB=postgres_test
    ports:
      - '5430:5432'
    networks:
      - custom
networks:
  custom:
    driver: bridge


# docker-compose up -d
# up — запускает контейнеры, указанные в файле конфигурации, и, если их нет, создает и запускает их.
# -d (detached mode) — запускает контейнеры в фоновом режиме, не блокируя текущий терминал.

#        '5430:5432'  - Левый порт-порт ОС, куда мы делаем запрос, правый - порт контейнера

# Чтобы подключиться к БД в контейнере докера через терминал винды:
#docker exec -it <container_name_or_id> bash   #подключиться к работающему контейнеру PostgreSQL
#psql -U <username> -d <database_name>      # подключение к PostgreSQL
